# примеры API-запросов доступных только для покупателей

@baseUrl = http://127.0.0.1:8000/api/v1

@email = "hello@hello.ru"
@email = "maafanasiev@mail.ru"
@password = "new_password2"
@confirm_token = "2f3c9"
@session_token = 2686fa12c322b7f3113bd9685a2d4eda1edb2935
@chng_pswrd_token = "217f6"

###
# получить корзину
GET {{baseUrl}}/basket
Content-Type: application/json
Authorization: Token {{session_token}}

###
# добавить товар в корзину
POST {{baseUrl}}/basket
Content-Type: application/json
Authorization: Token {{session_token}}

{ 
  "product_info": 14, 
  "quantity": 1
}

###
# изменить количество товара в корзине
PUT {{baseUrl}}/basket
Content-Type: application/json
Authorization: Token {{session_token}}

{ 
  "id": 4, 
  "quantity": 2
}

###
# удалить товар из корзины
DELETE {{baseUrl}}/basket
Content-Type: application/json
Authorization: Token {{session_token}}

{ 
  "id": "all"
}


###
# получить мои заказы
GET {{baseUrl}}/orders
Content-Type: application/json
Authorization: Token {{session_token}}

###
# детали заказа
GET {{baseUrl}}/order?id=8
Content-Type: application/json
Authorization: Token {{session_token}}

###
# разместить заказ из корзины
POST {{baseUrl}}/order
Content-Type: application/json
Authorization: Token {{session_token}}

{ 
  "id": 12, 
  "contact": 14
}
